name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 24.04

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run basic test
        run: |
          echo "✅ Placeholder test passed!"

      - name: Build Docker image
        run: docker build -t flask-devops-app .

      - name: Deployment (placeholder)
        run: echo "🚀 App would be deployed here."
